2021-06-25T15:17:18|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\laboratorio\anaconda3\envs\DMD\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\laboratorio\anaconda3\envs\DMD\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Programmi laboratorio\Python\ScopeFoundryProjects\VialuxDMD_ScopeFoundry\DMD_hw.py", line 49, in connect
    self.stop.hardware_set_func = self.vialux.stop
AttributeError: 'method' object has no attribute 'hardware_set_func'

